### ISSUE TITLE
Scrolling background

### ISSUE THREAD

**Issue by orkaboy** [ARCsweden/GameJam2024SpringA#11]

**Comment by TheWorkingBee** [comment]
TODO: Det ska vara två kolumner, med utrymme för gubben i mitten 
**1. I ready ska det skapas så många objekt att de fyller upp skärmen
2. Vi ska flytta skärmen med längd lika stor som spriten
3. Lägg till en ny sprite med rätt avståd så den ligger på nästa sprite**
**4. Rensa koden**
5. Smootha till
**7. Fixa glapp**
8. Ändra textur
9. Ta bort noder
